GET http://localhost:3000/users


###

GET http://localhost:3000/locks/userLocks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJoYXNQaW4iOnRydWUsImhhc0ZpbmdlcnByaW50IjpmYWxzZSwiaGFzUGF0dGVybiI6dHJ1ZSwiX2lkIjoiNjA3NDJjZjNkZTk1YzNlZjRkNTgwZDgzIiwibmFtZSI6Im1hciIsInBhc3N3b3JkIjoiJDJiJDEwJGZJdWNPYUtwZHlhSDNtTjM2Ym8vNXVMZ0dNaXMweTJzdVFkS2RsZ0RwYkQ5M2t1ZlRnZTZLIiwiX192IjowLCJpYXQiOjE2MTgyMjY1ODQsImV4cCI6MTYxODMxMjk4NH0.uxzAvufKcMaVFXeA0474myiKgPrgZNY6hNJS5ADDRis

###
GET http://localhost:3000/users/currentUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJoYXNQaW4iOnRydWUsImhhc0ZpbmdlcnByaW50IjpmYWxzZSwiaGFzUGF0dGVybiI6dHJ1ZSwiX2lkIjoiNjA3NDJjZjNkZTk1YzNlZjRkNTgwZDgzIiwibmFtZSI6Im1hciIsInBhc3N3b3JkIjoiJDJiJDEwJGZJdWNPYUtwZHlhSDNtTjM2Ym8vNXVMZ0dNaXMweTJzdVFkS2RsZ0RwYkQ5M2t1ZlRnZTZLIiwiX192IjowLCJpYXQiOjE2MTgyMjY1ODQsImV4cCI6MTYxODMxMjk4NH0.uxzAvufKcMaVFXeA0474myiKgPrgZNY6hNJS5ADDRis

# ###

DELETE http://localhost:3000/users/logout 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDU4OTc2MGNlNzQ0NDU5MmIzOTZlYjYiLCJuYW1lIjoiamEiLCJwYXNzd29yZCI6IiQyYiQxMCRFM0pDbWRaTVJ2SzYyalVwRjYzN2tPU3lMU09oZFVhLkh3d3RwZlVMcVdzbUk1OVJJaWIuQyIsIl9fdiI6MCwiaWF0IjoxNjE2NDE4NzQyfQ.Cs4IwTe3rz2zLZe8lY2mpE16OnS02EqTi6JxZ2ZVsl4"
}

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "A",
    "password": "AAA"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "nj",
    "password": "haslo"
}

###

POST http://localhost:3000/security/pin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDVjYzVjM2Y3NzE0MzQ5Mjg4NTE4OTMiLCJuYW1lIjoiTWFyY2luIiwicGFzc3dvcmQiOiIkMmIkMTAkVzF0OExaVFlBc2xRa3FCZGc3ZVVmLmx6WHBtbFlJdmZoem0xWk5HQmRiaERObnlMbXljOUciLCJfX3YiOjAsImlhdCI6MTYxNjk0MzEwMiwiZXhwIjoxNjE3MDI5NTAyfQ.WYQPQHgZYu6-J2Hy954qtFG_EeF4LvDkzexVs_khdzA

{
    "userId": "",
    "pin": "111111"
}
